# Generated by Django 5.1.7 on 2026-01-02 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_age', models.IntegerField(verbose_name='Tuổi')),
                ('person_income', models.IntegerField(verbose_name='Thu nhập')),
                ('person_home_ownership', models.CharField(max_length=20, verbose_name='Nhà ở')),
                ('person_emp_length', models.FloatField(verbose_name='Số năm làm việc')),
                ('loan_intent', models.CharField(max_length=50, verbose_name='Mục đích vay')),
                ('loan_grade', models.CharField(max_length=10, verbose_name='Xếp hạng')),
                ('loan_amnt', models.IntegerField(verbose_name='Số tiền vay yêu cầu')),
                ('loan_int_rate', models.FloatField(verbose_name='Lãi suất')),
                ('loan_percent_income', models.FloatField(verbose_name='Tỷ lệ vay/Thu nhập')),
                ('cb_person_default_on_file', models.CharField(max_length=5, verbose_name='Từng vỡ nợ')),
                ('cb_person_cred_hist_length', models.IntegerField(verbose_name='Lịch sử tín dụng (năm)')),
                ('ahp_score', models.FloatField(verbose_name='Điểm AHP')),
                ('ahp_weights', models.JSONField(null=True, verbose_name='Trọng số AHP')),
                ('ahp_criteria_scores', models.JSONField(null=True, verbose_name='Điểm từng tiêu chí')),
                ('consistency_ratio', models.FloatField(null=True, verbose_name='CR')),
                ('probability_default', models.FloatField(verbose_name='Xác suất nợ xấu')),
                ('model_accuracy', models.FloatField(null=True, verbose_name='Độ chính xác model')),
                ('final_score', models.FloatField(verbose_name='Điểm cuối cùng')),
                ('decision', models.CharField(max_length=50, verbose_name='Quyết định')),
                ('risk_level', models.CharField(max_length=50, verbose_name='Mức độ rủi ro')),
                ('recommended_amount', models.IntegerField(verbose_name='Số tiền đề xuất')),
                ('max_loan_amount', models.IntegerField(verbose_name='Hạn mức tối đa')),
                ('explanation', models.TextField(verbose_name='Giải thích')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian dự đoán')),
            ],
            options={
                'verbose_name': 'Dự đoán cho vay',
                'verbose_name_plural': 'Lịch sử dự đoán cho vay',
                'db_table': 'loan_predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
