# Generated by Django 5.1.7 on 2026-04-20 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanprediction',
            name='person_name',
            field=models.CharField(blank=True, default='Khách hàng', max_length=100, null=True, verbose_name='Họ và tên'),
        ),
        migrations.CreateModel(
            name='CreditRiskDatasetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_age', models.IntegerField(verbose_name='Tuổi')),
                ('person_income', models.IntegerField(verbose_name='Thu nhập')),
                ('person_home_ownership', models.CharField(max_length=20, verbose_name='Nhà ở')),
                ('person_emp_length', models.FloatField(blank=True, null=True, verbose_name='Số năm làm việc')),
                ('loan_intent', models.CharField(max_length=50, verbose_name='Mục đích vay')),
                ('loan_grade', models.CharField(max_length=10, verbose_name='Xếp hạng')),
                ('loan_amnt', models.IntegerField(verbose_name='Số tiền vay')),
                ('loan_int_rate', models.FloatField(blank=True, null=True, verbose_name='Lãi suất')),
                ('loan_percent_income', models.FloatField(blank=True, null=True, verbose_name='Tỷ lệ vay/Thu nhập')),
                ('cb_person_default_on_file', models.CharField(max_length=5, verbose_name='Từng vỡ nợ')),
                ('cb_person_cred_hist_length', models.IntegerField(verbose_name='Lịch sử tín dụng (năm)')),
                ('loan_status', models.IntegerField(verbose_name='Trạng thái khoản vay')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian import')),
            ],
            options={
                'verbose_name': 'Dòng dữ liệu Credit Risk',
                'verbose_name_plural': 'Dataset Credit Risk',
                'db_table': 'credit_risk_dataset',
                'indexes': [models.Index(fields=['loan_status'], name='credit_risk_loan_st_603e71_idx'), models.Index(fields=['loan_grade'], name='credit_risk_loan_gr_ff32a6_idx'), models.Index(fields=['loan_intent'], name='credit_risk_loan_in_162a60_idx')],
            },
        ),
    ]
